### PR TITLE
Update badgerdb and ristretto v0.2.0 to fix bugs on arm

### PR DESCRIPTION
**Pull request by atlas-comstock**

### CODE REVIEW

**Comment by kelindar** [comment]
Looks god, should we merge it @atlas-comstock ?

**Comment by atlas-comstock** [comment]
@kelindar plz wait, I 'll validate it today and tmr. thanks

**Comment by atlas-comstock** [comment]
We are using `talaria -> badgerDB ->  ristretto cache`(dep relationship) and as the `mmap issue` happened on `ristretto`, we have to fork badgerDB and  ristretto.

After forking, to make sure the dependency works well, we use `go module replace` like this: 
`replace github.com/dgraph-io/badger/v3 v3.2103.1 => github.com/atlas-comstock/badger/v3 v3.2103.1-with-arm-fix`

At last, I found that the `ristretto` still use the original version even though I had replaced it in my `github.com/atlas-comstock/badger/v3 v3.2103.1-with-arm-fix` version.
Therefore, I have to replace them both on talaria:
```
replace github.com/dgraph-io/badger/v3 v3.2103.1 => github.com/atlas-comstock/badger/v3 v3.2103.1-with-arm-fix

replace github.com/dgraph-io/ristretto v0.1.0 => github.com/atlas-comstock/ristretto v0.2.0
```

**Review by kelindar — APPROVED** [review]

**Comment by atlas-comstock** [comment]
Fix #92 #98

**Pull request merged**
